linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  revive:
    ignore-generated-header: false
    confidence: 0.3
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
    ignore-words: []

linters:
  disable-all: true
  enable:
    # HTTPリクエストで閉じられていないものを検出
    - bodyclose
    # _, _ := x() のようなものを検出
    - dogsled
    # 同一コードの検出
    - dupl
    # エラーを未チェックのものを検出
    - errcheck
    # 定数化できるものを検出
    - goconst
    # gofmt
    - gofmt
    # goimports
    - goimports
    # golint代替
    - revive
    # 引数がフォーマット文字列と一致しないものを検出
    - govet
    # 意味のない再代入を検出
    - ineffassign
    # スペルチェック
    - misspell
    # for中などで固定されてない変数を検出
    - exportloopref
    # 構造体の未使用フィールドを検出
    - staticcheck
    # 不要な型変換を検出
    - unconvert
    # 未使用のものを検出
    - unused
    # 前後の余計な空白を検出
    - whitespace

issues:
  exclude:
    - declaration of "(err|ctx)" shadows declaration at
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
    - linters:
        - staticcheck
      text: "SA1019: xerrors."

service:
  golangci-lint-version: 1.49.x
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
