// Code generated by volcago. DO NOT EDIT.
// generated version: devel
package model

const (
	SubTaskIndexLabelIsSubCollectionPrefix = "i1" // prefix-match of IsSubCollection
	SubTaskIndexLabelIsSubCollectionSuffix = "i2" // suffix-match of IsSubCollection
	SubTaskIndexLabelIsSubCollectionLike   = "i3" // like-match of IsSubCollection
	SubTaskIndexLabelIsSubCollectionEqual  = "i4" // perfect-match of IsSubCollection
)
