// Code generated by volcago. DO NOT EDIT.
// generated version: devel
package model

const (
	TaskIndexLabelDescEqual          = "d4"  // perfect-match of Desc
	TaskIndexLabelDescLike           = "d3"  // like-match of Desc
	TaskIndexLabelDescPrefix         = "d1"  // prefix-match of Desc
	TaskIndexLabelDescSuffix         = "d2"  // suffix-match of Desc
	TaskIndexLabelDesc2Equal         = "d8"  // perfect-match of Desc2
	TaskIndexLabelDesc2Like          = "d7"  // like-match of Desc2
	TaskIndexLabelDesc2Prefix        = "d5"  // prefix-match of Desc2
	TaskIndexLabelDesc2Suffix        = "d6"  // suffix-match of Desc2
	TaskIndexLabelCreatedPrefix      = "c1"  // prefix-match of Created
	TaskIndexLabelCreatedSuffix      = "c2"  // suffix-match of Created
	TaskIndexLabelCreatedLike        = "c3"  // like-match of Created
	TaskIndexLabelCreatedEqual       = "c4"  // perfect-match of Created
	TaskIndexLabelReservedDatePrefix = "r1"  // prefix-match of ReservedDate
	TaskIndexLabelReservedDateSuffix = "r2"  // suffix-match of ReservedDate
	TaskIndexLabelReservedDateLike   = "r3"  // like-match of ReservedDate
	TaskIndexLabelReservedDateEqual  = "r4"  // perfect-match of ReservedDate
	TaskIndexLabelDonePrefix         = "d9"  // prefix-match of Done
	TaskIndexLabelDoneSuffix         = "do1" // suffix-match of Done
	TaskIndexLabelDoneLike           = "do2" // like-match of Done
	TaskIndexLabelDoneEqual          = "do3" // perfect-match of Done
	TaskIndexLabelDone2Prefix        = "do4" // prefix-match of Done2
	TaskIndexLabelDone2Suffix        = "do5" // suffix-match of Done2
	TaskIndexLabelDone2Like          = "do6" // like-match of Done2
	TaskIndexLabelDone2Equal         = "do7" // perfect-match of Done2
	TaskIndexLabelCountPrefix        = "c5"  // prefix-match of Count
	TaskIndexLabelCountSuffix        = "c6"  // suffix-match of Count
	TaskIndexLabelCountLike          = "c7"  // like-match of Count
	TaskIndexLabelCountEqual         = "c8"  // perfect-match of Count
	TaskIndexLabelCount64Prefix      = "c9"  // prefix-match of Count64
	TaskIndexLabelCount64Suffix      = "co1" // suffix-match of Count64
	TaskIndexLabelCount64Like        = "co2" // like-match of Count64
	TaskIndexLabelCount64Equal       = "co3" // perfect-match of Count64
	TaskIndexLabelNameListPrefix     = "n1"  // prefix-match of NameList
	TaskIndexLabelNameListSuffix     = "n2"  // suffix-match of NameList
	TaskIndexLabelNameListLike       = "n3"  // like-match of NameList
	TaskIndexLabelNameListEqual      = "n4"  // perfect-match of NameList
	TaskIndexLabelProportionPrefix   = "p1"  // prefix-match of Proportion
	TaskIndexLabelProportionSuffix   = "p2"  // suffix-match of Proportion
	TaskIndexLabelProportionLike     = "p3"  // like-match of Proportion
	TaskIndexLabelProportionEqual    = "p4"  // perfect-match of Proportion
	TaskIndexLabelGeoPrefix          = "g1"  // prefix-match of Geo
	TaskIndexLabelGeoSuffix          = "g2"  // suffix-match of Geo
	TaskIndexLabelGeoLike            = "g3"  // like-match of Geo
	TaskIndexLabelGeoEqual           = "g4"  // perfect-match of Geo
	TaskIndexLabelSubPrefix          = "s1"  // prefix-match of Sub
	TaskIndexLabelSubSuffix          = "s2"  // suffix-match of Sub
	TaskIndexLabelSubLike            = "s3"  // like-match of Sub
	TaskIndexLabelSubEqual           = "s4"  // perfect-match of Sub
	TaskIndexLabelFlagPrefix         = "f1"  // prefix-match of Flag
	TaskIndexLabelFlagSuffix         = "f2"  // suffix-match of Flag
	TaskIndexLabelFlagLike           = "f3"  // like-match of Flag
	TaskIndexLabelFlagEqual          = "f4"  // perfect-match of Flag
)
