// Code generated by volcago. DO NOT EDIT.
// generated version: (devel)
package repository

const (
	LockIndexLabelTextEqual            = "t4" // perfect-match of Text
	LockIndexLabelTextLike             = "t3" // like-match of Text
	LockIndexLabelTextPrefix           = "t1" // prefix-match of Text
	LockIndexLabelTextSuffix           = "t2" // suffix-match of Text
	LockIndexLabelFlagPrefix           = "f1" // prefix-match of Flag
	LockIndexLabelFlagSuffix           = "f2" // suffix-match of Flag
	LockIndexLabelFlagLike             = "f3" // like-match of Flag
	LockIndexLabelFlagEqual            = "f4" // perfect-match of Flag
	LockIndexLabelInterfacePrefix      = "i1" // prefix-match of Interface
	LockIndexLabelInterfaceSuffix      = "i2" // suffix-match of Interface
	LockIndexLabelInterfaceLike        = "i3" // like-match of Interface
	LockIndexLabelInterfaceEqual       = "i4" // perfect-match of Interface
	LockIndexLabelMapInterfacePrefix   = "m1" // prefix-match of MapInterface
	LockIndexLabelMapInterfaceSuffix   = "m2" // suffix-match of MapInterface
	LockIndexLabelMapInterfaceLike     = "m3" // like-match of MapInterface
	LockIndexLabelMapInterfaceEqual    = "m4" // perfect-match of MapInterface
	LockIndexLabelNested_NameEqual     = "n4" // perfect-match of Nested.Name
	LockIndexLabelNested_NameLike      = "n3" // like-match of Nested.Name
	LockIndexLabelNested_NamePrefix    = "n1" // prefix-match of Nested.Name
	LockIndexLabelNested_NameSuffix    = "n2" // suffix-match of Nested.Name
	LockIndexLabelNestedPtr_NameEqual  = "n8" // perfect-match of NestedPtr.Name
	LockIndexLabelNestedPtr_NameLike   = "n7" // like-match of NestedPtr.Name
	LockIndexLabelNestedPtr_NamePrefix = "n5" // prefix-match of NestedPtr.Name
	LockIndexLabelNestedPtr_NameSuffix = "n6" // suffix-match of NestedPtr.Name
	LockIndexLabelCreatedAtPrefix      = "c1" // prefix-match of CreatedAt
	LockIndexLabelCreatedAtSuffix      = "c2" // suffix-match of CreatedAt
	LockIndexLabelCreatedAtLike        = "c3" // like-match of CreatedAt
	LockIndexLabelCreatedAtEqual       = "c4" // perfect-match of CreatedAt
	LockIndexLabelCreatedByEqual       = "c8" // perfect-match of CreatedBy
	LockIndexLabelCreatedByLike        = "c7" // like-match of CreatedBy
	LockIndexLabelCreatedByPrefix      = "c5" // prefix-match of CreatedBy
	LockIndexLabelCreatedBySuffix      = "c6" // suffix-match of CreatedBy
	LockIndexLabelUpdatedAtPrefix      = "u1" // prefix-match of UpdatedAt
	LockIndexLabelUpdatedAtSuffix      = "u2" // suffix-match of UpdatedAt
	LockIndexLabelUpdatedAtLike        = "u3" // like-match of UpdatedAt
	LockIndexLabelUpdatedAtEqual       = "u4" // perfect-match of UpdatedAt
	LockIndexLabelUpdatedByEqual       = "u8" // perfect-match of UpdatedBy
	LockIndexLabelUpdatedByLike        = "u7" // like-match of UpdatedBy
	LockIndexLabelUpdatedByPrefix      = "u5" // prefix-match of UpdatedBy
	LockIndexLabelUpdatedBySuffix      = "u6" // suffix-match of UpdatedBy
	LockIndexLabelDeletedAtPrefix      = "d1" // prefix-match of DeletedAt
	LockIndexLabelDeletedAtSuffix      = "d2" // suffix-match of DeletedAt
	LockIndexLabelDeletedAtLike        = "d3" // like-match of DeletedAt
	LockIndexLabelDeletedAtEqual       = "d4" // perfect-match of DeletedAt
	LockIndexLabelDeletedByEqual       = "d8" // perfect-match of DeletedBy
	LockIndexLabelDeletedByLike        = "d7" // like-match of DeletedBy
	LockIndexLabelDeletedByPrefix      = "d5" // prefix-match of DeletedBy
	LockIndexLabelDeletedBySuffix      = "d6" // suffix-match of DeletedBy
	LockIndexLabelVersionPrefix        = "v1" // prefix-match of Version
	LockIndexLabelVersionSuffix        = "v2" // suffix-match of Version
	LockIndexLabelVersionLike          = "v3" // like-match of Version
	LockIndexLabelVersionEqual         = "v4" // perfect-match of Version
)
