// Code generated by volcago. DO NOT EDIT.
// generated version: (devel)
package model

const (
	LockMetaIndexLabelTextEqual       = "t4" // perfect-match of Text
	LockMetaIndexLabelTextLike        = "t3" // like-match of Text
	LockMetaIndexLabelTextPrefix      = "t1" // prefix-match of Text
	LockMetaIndexLabelTextSuffix      = "t2" // suffix-match of Text
	LockMetaIndexLabelFlagPrefix      = "f1" // prefix-match of Flag
	LockMetaIndexLabelFlagSuffix      = "f2" // suffix-match of Flag
	LockMetaIndexLabelFlagLike        = "f3" // like-match of Flag
	LockMetaIndexLabelFlagEqual       = "f4" // perfect-match of Flag
	LockMetaIndexLabelCreatedAtPrefix = "c1" // prefix-match of CreatedAt
	LockMetaIndexLabelCreatedAtSuffix = "c2" // suffix-match of CreatedAt
	LockMetaIndexLabelCreatedAtLike   = "c3" // like-match of CreatedAt
	LockMetaIndexLabelCreatedAtEqual  = "c4" // perfect-match of CreatedAt
	LockMetaIndexLabelCreatedByEqual  = "c8" // perfect-match of CreatedBy
	LockMetaIndexLabelCreatedByLike   = "c7" // like-match of CreatedBy
	LockMetaIndexLabelCreatedByPrefix = "c5" // prefix-match of CreatedBy
	LockMetaIndexLabelCreatedBySuffix = "c6" // suffix-match of CreatedBy
	LockMetaIndexLabelUpdatedAtPrefix = "u1" // prefix-match of UpdatedAt
	LockMetaIndexLabelUpdatedAtSuffix = "u2" // suffix-match of UpdatedAt
	LockMetaIndexLabelUpdatedAtLike   = "u3" // like-match of UpdatedAt
	LockMetaIndexLabelUpdatedAtEqual  = "u4" // perfect-match of UpdatedAt
	LockMetaIndexLabelUpdatedByEqual  = "u8" // perfect-match of UpdatedBy
	LockMetaIndexLabelUpdatedByLike   = "u7" // like-match of UpdatedBy
	LockMetaIndexLabelUpdatedByPrefix = "u5" // prefix-match of UpdatedBy
	LockMetaIndexLabelUpdatedBySuffix = "u6" // suffix-match of UpdatedBy
	LockMetaIndexLabelDeletedAtPrefix = "d1" // prefix-match of DeletedAt
	LockMetaIndexLabelDeletedAtSuffix = "d2" // suffix-match of DeletedAt
	LockMetaIndexLabelDeletedAtLike   = "d3" // like-match of DeletedAt
	LockMetaIndexLabelDeletedAtEqual  = "d4" // perfect-match of DeletedAt
	LockMetaIndexLabelDeletedByEqual  = "d8" // perfect-match of DeletedBy
	LockMetaIndexLabelDeletedByLike   = "d7" // like-match of DeletedBy
	LockMetaIndexLabelDeletedByPrefix = "d5" // prefix-match of DeletedBy
	LockMetaIndexLabelDeletedBySuffix = "d6" // suffix-match of DeletedBy
	LockMetaIndexLabelVersionPrefix   = "v1" // prefix-match of Version
	LockMetaIndexLabelVersionSuffix   = "v2" // suffix-match of Version
	LockMetaIndexLabelVersionLike     = "v3" // like-match of Version
	LockMetaIndexLabelVersionEqual    = "v4" // perfect-match of Version
)
