// Code generated by volcago. DO NOT EDIT.
// generated version: (devel)
package model

const (
	LockMeta2IndexLabelTextEqual       = "t4" // perfect-match of Text
	LockMeta2IndexLabelTextLike        = "t3" // like-match of Text
	LockMeta2IndexLabelTextPrefix      = "t1" // prefix-match of Text
	LockMeta2IndexLabelTextSuffix      = "t2" // suffix-match of Text
	LockMeta2IndexLabelFlagPrefix      = "f1" // prefix-match of Flag
	LockMeta2IndexLabelFlagSuffix      = "f2" // suffix-match of Flag
	LockMeta2IndexLabelFlagLike        = "f3" // like-match of Flag
	LockMeta2IndexLabelFlagEqual       = "f4" // perfect-match of Flag
	LockMeta2IndexLabelCreatedAtPrefix = "c1" // prefix-match of CreatedAt
	LockMeta2IndexLabelCreatedAtSuffix = "c2" // suffix-match of CreatedAt
	LockMeta2IndexLabelCreatedAtLike   = "c3" // like-match of CreatedAt
	LockMeta2IndexLabelCreatedAtEqual  = "c4" // perfect-match of CreatedAt
	LockMeta2IndexLabelCreatedByEqual  = "c8" // perfect-match of CreatedBy
	LockMeta2IndexLabelCreatedByLike   = "c7" // like-match of CreatedBy
	LockMeta2IndexLabelCreatedByPrefix = "c5" // prefix-match of CreatedBy
	LockMeta2IndexLabelCreatedBySuffix = "c6" // suffix-match of CreatedBy
	LockMeta2IndexLabelUpdatedAtPrefix = "u1" // prefix-match of UpdatedAt
	LockMeta2IndexLabelUpdatedAtSuffix = "u2" // suffix-match of UpdatedAt
	LockMeta2IndexLabelUpdatedAtLike   = "u3" // like-match of UpdatedAt
	LockMeta2IndexLabelUpdatedAtEqual  = "u4" // perfect-match of UpdatedAt
	LockMeta2IndexLabelUpdatedByEqual  = "u8" // perfect-match of UpdatedBy
	LockMeta2IndexLabelUpdatedByLike   = "u7" // like-match of UpdatedBy
	LockMeta2IndexLabelUpdatedByPrefix = "u5" // prefix-match of UpdatedBy
	LockMeta2IndexLabelUpdatedBySuffix = "u6" // suffix-match of UpdatedBy
	LockMeta2IndexLabelDeletedAtPrefix = "d1" // prefix-match of DeletedAt
	LockMeta2IndexLabelDeletedAtSuffix = "d2" // suffix-match of DeletedAt
	LockMeta2IndexLabelDeletedAtLike   = "d3" // like-match of DeletedAt
	LockMeta2IndexLabelDeletedAtEqual  = "d4" // perfect-match of DeletedAt
	LockMeta2IndexLabelDeletedByEqual  = "d8" // perfect-match of DeletedBy
	LockMeta2IndexLabelDeletedByLike   = "d7" // like-match of DeletedBy
	LockMeta2IndexLabelDeletedByPrefix = "d5" // prefix-match of DeletedBy
	LockMeta2IndexLabelDeletedBySuffix = "d6" // suffix-match of DeletedBy
	LockMeta2IndexLabelVersionPrefix   = "v1" // prefix-match of Version
	LockMeta2IndexLabelVersionSuffix   = "v2" // suffix-match of Version
	LockMeta2IndexLabelVersionLike     = "v3" // like-match of Version
	LockMeta2IndexLabelVersionEqual    = "v4" // perfect-match of Version
)
