// Code generated by volcago. DO NOT EDIT.
// generated version: (devel)
package model

const (
	SubCollectionIndexLabelFlagPrefix = "f1" // prefix-match of Flag
	SubCollectionIndexLabelFlagSuffix = "f2" // suffix-match of Flag
	SubCollectionIndexLabelFlagLike   = "f3" // like-match of Flag
	SubCollectionIndexLabelFlagEqual  = "f4" // perfect-match of Flag
)
