// Code generated by volcago. DO NOT EDIT.
// generated version: (devel)
package model

const (
	SubTaskIndexLabelFlagPrefix = "f1" // prefix-match of Flag
	SubTaskIndexLabelFlagSuffix = "f2" // suffix-match of Flag
	SubTaskIndexLabelFlagLike   = "f3" // like-match of Flag
	SubTaskIndexLabelFlagEqual  = "f4" // perfect-match of Flag
)
