project_name: volcago
version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: volcago
    ldflags:
      - -s -w
      - -X main.AppVersion=v{{ .Version }}
    env:
      - CGO_ENABLED=0

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: auto
