// Code generated by volcago. DO NOT EDIT.
// generated version: (devel)
package examples

const (
	HistoryIndexLabelIsSubCollectionPrefix = "i1" // prefix-match of IsSubCollection
	HistoryIndexLabelIsSubCollectionSuffix = "i2" // suffix-match of IsSubCollection
	HistoryIndexLabelIsSubCollectionLike   = "i3" // like-match of IsSubCollection
	HistoryIndexLabelIsSubCollectionEqual  = "i4" // perfect-match of IsSubCollection
)
